// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountStructs.proto

#include "AccountStructs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace AccountServiceIPC {
}  // namespace AccountServiceIPC
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_AccountStructs_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_AccountStructs_2eproto = nullptr;
const uint32_t TableStruct_AccountStructs_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_AccountStructs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024AccountStructs.proto\022\021AccountServiceIP"
  "C*\342\001\n\030AccountHandlerStatusCode\022\036\n\032Accoun"
  "tSuccessfullyCreated\020\000\022\036\n\032AccountSuccess"
  "fullyDeleted\020\001\022\030\n\024AccountAlreadyExists\020\002"
  "\022\031\n\025AccountCouldntBeFound\020\003\022\031\n\025FailedToC"
  "reateAccount\020\004\022\031\n\025FailedToDeleteAccount\020"
  "\005\022\033\n\027NotAuthenticatedAccount\020\006*[\n\037Accoun"
  "tAuthenticationStatusCode\022\030\n\024Authenticat"
  "edAccount\020\000\022\036\n\032ErrorAuthenticationAccoun"
  "t\020\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_AccountStructs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_AccountStructs_2eproto = {
    false, false, 371, descriptor_table_protodef_AccountStructs_2eproto,
    "AccountStructs.proto",
    &descriptor_table_AccountStructs_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_AccountStructs_2eproto::offsets,
    nullptr, file_level_enum_descriptors_AccountStructs_2eproto,
    file_level_service_descriptors_AccountStructs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_AccountStructs_2eproto_getter() {
  return &descriptor_table_AccountStructs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_AccountStructs_2eproto(&descriptor_table_AccountStructs_2eproto);
namespace AccountServiceIPC {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountHandlerStatusCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AccountStructs_2eproto);
  return file_level_enum_descriptors_AccountStructs_2eproto[0];
}
bool AccountHandlerStatusCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountAuthenticationStatusCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AccountStructs_2eproto);
  return file_level_enum_descriptors_AccountStructs_2eproto[1];
}
bool AccountAuthenticationStatusCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace AccountServiceIPC
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
