// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AccountServiceIPC.proto
#ifndef GRPC_AccountServiceIPC_2eproto__INCLUDED
#define GRPC_AccountServiceIPC_2eproto__INCLUDED

#include "AccountServiceIPC.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace AccountServiceIPC {

class AccountServiceIPC final {
 public:
  static constexpr char const* service_full_name() {
    return "AccountServiceIPC.AccountServiceIPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::AccountServiceIPC::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>> AsyncPing(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>> PrepareAsyncPing(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>>(PrepareAsyncPingRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::AccountServiceIPC::CreateAccountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>> AsyncCreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>>(AsyncCreateAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>> PrepareAsyncCreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>>(PrepareAsyncCreateAccountRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::AccountServiceIPC::DeleteAccountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>> AsyncDeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>>(AsyncDeleteAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>> PrepareAsyncDeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>>(PrepareAsyncDeleteAccountRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>* AsyncPingRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::Empty>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>* AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::CreateAccountResponse>* PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>* AsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AccountServiceIPC::DeleteAccountResponse>* PrepareAsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::AccountServiceIPC::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>> AsyncPing(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>> PrepareAsyncPing(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>>(PrepareAsyncPingRaw(context, request, cq));
    }
    ::grpc::Status CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::AccountServiceIPC::CreateAccountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>> AsyncCreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>>(AsyncCreateAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>> PrepareAsyncCreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>>(PrepareAsyncCreateAccountRaw(context, request, cq));
    }
    ::grpc::Status DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::AccountServiceIPC::DeleteAccountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>> AsyncDeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>>(AsyncDeleteAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>> PrepareAsyncDeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>>(PrepareAsyncDeleteAccountRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response, std::function<void(::grpc::Status)>) override;
      void Ping(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteAccount(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>* AsyncPingRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::Empty>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>* AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::CreateAccountResponse>* PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::CreateAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>* AsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AccountServiceIPC::DeleteAccountResponse>* PrepareAsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::AccountServiceIPC::DeleteAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ping_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateAccount_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteAccount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response);
    virtual ::grpc::Status CreateAccount(::grpc::ServerContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response);
    virtual ::grpc::Status DeleteAccount(::grpc::ServerContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::AccountServiceIPC::Empty* request, ::grpc::ServerAsyncResponseWriter< ::AccountServiceIPC::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateAccount() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateAccount(::grpc::ServerContext* context, ::AccountServiceIPC::CreateAccountRequest* request, ::grpc::ServerAsyncResponseWriter< ::AccountServiceIPC::CreateAccountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAccount(::grpc::ServerContext* context, ::AccountServiceIPC::DeleteAccountRequest* request, ::grpc::ServerAsyncResponseWriter< ::AccountServiceIPC::DeleteAccountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ping<WithAsyncMethod_CreateAccount<WithAsyncMethod_DeleteAccount<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::Empty, ::AccountServiceIPC::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AccountServiceIPC::Empty* request, ::AccountServiceIPC::Empty* response) { return this->Ping(context, request, response); }));}
    void SetMessageAllocatorFor_Ping(
        ::grpc::MessageAllocator< ::AccountServiceIPC::Empty, ::AccountServiceIPC::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::Empty, ::AccountServiceIPC::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateAccount() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::CreateAccountRequest, ::AccountServiceIPC::CreateAccountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AccountServiceIPC::CreateAccountRequest* request, ::AccountServiceIPC::CreateAccountResponse* response) { return this->CreateAccount(context, request, response); }));}
    void SetMessageAllocatorFor_CreateAccount(
        ::grpc::MessageAllocator< ::AccountServiceIPC::CreateAccountRequest, ::AccountServiceIPC::CreateAccountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::CreateAccountRequest, ::AccountServiceIPC::CreateAccountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::DeleteAccountRequest, ::AccountServiceIPC::DeleteAccountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AccountServiceIPC::DeleteAccountRequest* request, ::AccountServiceIPC::DeleteAccountResponse* response) { return this->DeleteAccount(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteAccount(
        ::grpc::MessageAllocator< ::AccountServiceIPC::DeleteAccountRequest, ::AccountServiceIPC::DeleteAccountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AccountServiceIPC::DeleteAccountRequest, ::AccountServiceIPC::DeleteAccountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ping<WithCallbackMethod_CreateAccount<WithCallbackMethod_DeleteAccount<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateAccount() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateAccount() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateAccount() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AccountServiceIPC::Empty, ::AccountServiceIPC::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AccountServiceIPC::Empty, ::AccountServiceIPC::Empty>* streamer) {
                       return this->StreamedPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::Empty* /*request*/, ::AccountServiceIPC::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AccountServiceIPC::Empty,::AccountServiceIPC::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateAccount() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AccountServiceIPC::CreateAccountRequest, ::AccountServiceIPC::CreateAccountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AccountServiceIPC::CreateAccountRequest, ::AccountServiceIPC::CreateAccountResponse>* streamer) {
                       return this->StreamedCreateAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::CreateAccountRequest* /*request*/, ::AccountServiceIPC::CreateAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AccountServiceIPC::CreateAccountRequest,::AccountServiceIPC::CreateAccountResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteAccount() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AccountServiceIPC::DeleteAccountRequest, ::AccountServiceIPC::DeleteAccountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AccountServiceIPC::DeleteAccountRequest, ::AccountServiceIPC::DeleteAccountResponse>* streamer) {
                       return this->StreamedDeleteAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteAccount(::grpc::ServerContext* /*context*/, const ::AccountServiceIPC::DeleteAccountRequest* /*request*/, ::AccountServiceIPC::DeleteAccountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AccountServiceIPC::DeleteAccountRequest,::AccountServiceIPC::DeleteAccountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_CreateAccount<WithStreamedUnaryMethod_DeleteAccount<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_CreateAccount<WithStreamedUnaryMethod_DeleteAccount<Service > > > StreamedService;
};

}  // namespace AccountServiceIPC


#endif  // GRPC_AccountServiceIPC_2eproto__INCLUDED
